---
title: "Distances Between Observations"
author: "Amy Truong"
format:
  html:
    theme: flatly
    toc: true
    embed-resources: true
---

# Distances Between Observations

Read this notebook from top to bottom and fill in the code as you go. Work together and discuss with other students in the class. Try to resolve any errors on your own first, but don't get stuck; ask for help!

In addition to writing and running code, be sure to examine any output and interpret the results before moving on.

For many of these questions, there are several approaches, and there is no single right answer. You should try a few different things and compare with your classmates.

We will use `scikit-learn` extensively later, but for this activity you might want to stick with `pandas`.

In [1]:
import pandas as pd
import numpy as np

df_ames = pd.read_csv("https://dlsun.github.io/pods/data/AmesHousing.txt", sep = "\t")

df_ames.shape

(2930, 82)

## Ames - Recommending Similar Homes

1\. Suppose that you really like house 0 in the Ames housing data set, but it is too expensive. Find cheaper homes that are similar to it --- in terms of living area, number of bedrooms, number of bathrooms --- by calculating distances from house 0. You might want to try different distance metrics and different scaling methods; how sensitive are your results to these choices?

Be sure to actually look at the profiles of the homes that your algorithm picked out as most similar (based on these 3 variables). Do they make sense?

_Think:_ If the goal is to find a "good deal" on a similar house, should sale price be included as a variable in your distance metric?

In [2]:
df_ames["Bathrooms"] = df_ames["Full Bath"] + 0.5 * df_ames["Half Bath"]

house0 = df_ames.loc[0]
show_vars = ["Gr Liv Area", "Bedroom AbvGr", "Bathrooms", "House Style", "Neighborhood", "Year Built", "SalePrice"]

house0[show_vars]

Gr Liv Area        1656
Bedroom AbvGr         3
Bathrooms           1.0
House Style      1Story
Neighborhood      NAmes
Year Built         1960
SalePrice        215000
Name: 0, dtype: object

In [3]:
features = ["Gr Liv Area", "Bedroom AbvGr", "Bathrooms"]
X = df_ames[features].astype(float)

X_z = (X - X.mean()) / X.std()
X_z

diff = X_z - X_z.loc[0]
diff

df_ames["dist_euclid"] = np.sqrt((diff)**2).sum(axis = 1)
df_ames["dist_euclid"]
df_ames["dist_manhattan"] = diff.abs().sum(axis=1)

df_cheaper_sales_price = df_ames[df_ames["SalePrice"]<house0["SalePrice"]]
df_cheaper_sales_price.sort_values("dist_euclid")[show_vars + ["dist_euclid"]].head(10)

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,dist_euclid
1226,1661,3,1.0,SLvl,NAmes,1955,165500,0.009891
1940,1647,3,1.0,1Story,NAmes,1953,153000,0.017804
1357,1666,3,1.0,2Story,OldTown,1925,161000,0.019782
758,1666,3,1.0,1.5Fin,IDOTRR,1927,135000,0.019782
291,1666,3,1.0,1.5Fin,SWISU,1931,100000,0.019782
2637,1668,3,1.0,1.5Fin,OldTown,1948,135000,0.023738
618,1644,3,1.0,1Story,NAmes,1953,167000,0.023738
2700,1640,3,1.0,1Story,Sawyer,1950,131000,0.031651
1529,1639,3,1.0,1.5Fin,SWISU,1936,115000,0.033629
179,1633,3,1.0,1.5Fin,OldTown,1948,129000,0.045499

In [4]:
df_cheaper_sales_price.sort_values("dist_manhattan")[show_vars + ["dist_manhattan"]].head(10)

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,dist_manhattan
1226,1661,3,1.0,SLvl,NAmes,1955,165500,0.009891
1940,1647,3,1.0,1Story,NAmes,1953,153000,0.017804
1357,1666,3,1.0,2Story,OldTown,1925,161000,0.019782
758,1666,3,1.0,1.5Fin,IDOTRR,1927,135000,0.019782
291,1666,3,1.0,1.5Fin,SWISU,1931,100000,0.019782
2637,1668,3,1.0,1.5Fin,OldTown,1948,135000,0.023738
618,1644,3,1.0,1Story,NAmes,1953,167000,0.023738
2700,1640,3,1.0,1Story,Sawyer,1950,131000,0.031651
1529,1639,3,1.0,1.5Fin,SWISU,1936,115000,0.033629
179,1633,3,1.0,1.5Fin,OldTown,1948,129000,0.045499

**Yes, they do make sense. If we compare the characteristics of house 0 to the other homes, we can see that the characteristics are similar. More specifically, because we wanted living area, bedrooms, and bathrooms to be the same, we got similar houses with those characteristics. The one with the smallest distance is most similar.**

2\. Continuing part 1. Suppose that you really like house 0 in the data set, but it is too expensive. Find cheaper homes that are similar to it --- in terms of living area, number of bedrooms, number of bathrooms, **and House Style** --- by calculating distances from house 0. You might want to try different distance metrics and different scaling methods; how sensitive are your results to these choices?

Be sure to actually look at the profiles of the homes that your algorithm picked out as most similar. Do they make sense?

In [5]:
features_q2 = ["Gr Liv Area", "Bedroom AbvGr", "Bathrooms", "House Style"]
X_q2 = pd.get_dummies(df_ames[features_q2], drop_first=True).astype(float)
X_q2_z = (X_q2 - X_q2.mean()) / X_q2.std()

diff_q2 = X_q2_z - X_q2_z.loc[0]
df_ames["dist_euclid_q2"] = np.sqrt((diff_q2**2).sum(axis=1))

df_cheaper_q2 = df_ames[df_ames["SalePrice"] < house0["SalePrice"]]
df_cheaper_q2.sort_values("dist_euclid_q2")[show_vars + ["dist_euclid_q2"]].head(10)

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,dist_euclid_q2
1940,1647,3,1.0,1Story,NAmes,1953,153000,0.017804
618,1644,3,1.0,1Story,NAmes,1953,167000,0.023738
2700,1640,3,1.0,1Story,Sawyer,1950,131000,0.031651
314,1687,3,1.0,1Story,Timber,1948,160000,0.061324
788,1689,3,1.0,1Story,Edwards,1956,127500,0.065281
2282,1622,3,1.0,1Story,Mitchel,1961,168000,0.067259
2298,1608,3,1.0,1Story,Mitchel,1961,80000,0.094954
1240,1570,3,1.0,1Story,NAmes,1958,166800,0.170126
970,1771,3,1.0,1Story,Mitchel,1960,115000,0.227494
1410,1509,3,1.0,1Story,Edwards,1956,159900,0.290796

**Yes, these homes make sense. Now that we wanted to also account for the same house style, we are getting homes with the same house style, living area, bedrooms, and bathrooms. The home with the smallest distance have all of these characteristics and other similar ones to house 0. Again, the results are somewhat sensitive. By adding house style, the euclidian distance increased.**

3\. Continuing parts 1 and 2. Suppose that you really like house 0 in the data set, but it is too expensive. Find cheaper homes that are similar to it, by calculating distances. You can **choose the variables to include, but include both quantitative and categorical variables**. Be sure to actually look at the profiles of the homes that your algorithm picked out as most similar. Do they make sense?

You might want to try different distance metrics and different scaling methods; how sensitive are your results to these choices?

_Hint:_ There are many variables in the data set. Do not attempt to compute distance based on all the variables! You will want to pare down the number of variables, but be sure to include a mixture of categorical and quantitative variables. Refer to the [data documentation](https://ww2.amstat.org/publications/jse/v19n3/decock/DataDocumentation.txt) for information about the variables.

In [9]:
features_q3 = ["Gr Liv Area", "Bathrooms", "House Style", "Year Built", "Neighborhood"]
X_q3 = pd.get_dummies(df_ames[features_q3], drop_first=True).astype(float)
X_q3_z = (X_q3 - X_q3.mean()) / X_q3.std()

diff_q3 = X_q3_z - X_q3_z.loc[0]
df_ames["dist_euclid_q3"] = np.sqrt((diff_q3**2).sum(axis=1))

df_cheaper_q3 = df_ames[df_ames["SalePrice"] < house0["SalePrice"]]
df_cheaper_q3.sort_values("dist_euclid_q3")[show_vars + ["dist_euclid_q3"]].head(10)

,Gr Liv Area,Bedroom AbvGr,Bathrooms,House Style,Neighborhood,Year Built,SalePrice,dist_euclid_q3
2618,1600,2,1.0,1Story,NAmes,1957,207500,0.148696
1924,1721,4,1.0,1Story,NAmes,1957,174850,0.162395
1240,1570,3,1.0,1Story,NAmes,1958,166800,0.182525
1940,1647,3,1.0,1Story,NAmes,1953,153000,0.232124
618,1644,3,1.0,1Story,NAmes,1953,167000,0.232655
617,1691,2,1.0,1Story,NAmes,1967,175000,0.241575
2559,1624,2,1.0,1Story,NAmes,1952,146500,0.271973
616,1505,2,1.0,1Story,NAmes,1953,149500,0.377878
2558,1433,3,1.0,1Story,NAmes,1961,161000,0.442377
1896,1429,3,1.0,1Story,NAmes,1960,181900,0.449052

**Yes, these all make sense. Because I was not looking for houses with the same bedroom average and sale price, those features vary more, but for the other features I specified, they are the same.The euclidian distance is greater for these, probably due to the fact I didn't specify certain features of house 0. The rests appear to be somewhat sensitive to differnt distance and scaling methods. By incorporating Neighborhood, the distance increased.**

## Colleges similar to Cal Poly

We'll use data from the [College Scorecard data](https://collegescorecard.ed.gov/) to find colleges and universities that are similar to Cal Poly.

In [11]:
df_college = pd.read_csv("https://datasci112.stanford.edu/data/college_attributes.csv")

df_college.set_index("Institution", inplace = True)

df_college

,City,State,AdmissionRate,Undergraduates,CarnegieClassification,Ownership,PCIP01,PCIP03,PCIP04,PCIP05,...,PCIP44,PCIP45,PCIP46,PCIP47,PCIP48,PCIP49,PCIP50,PCIP51,PCIP52,PCIP54
Institution,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,0.7160,5098.0,Master's Colleges & Universities: Larger Programs,Public,0.0445,0.0071,0.0053,0.0000,...,0.0409,0.0249,0.0,0.0,0.0,0.0,0.0231,0.0000,0.1637,0.0000
University of Alabama at Birmingham,Birmingham,AL,0.8854,13284.0,Doctoral Universities: Very High Research Acti...,Public,0.0000,0.0000,0.0000,0.0020,...,0.0195,0.0239,0.0,0.0,0.0,0.0,0.0249,0.2088,0.2159,0.0141
University of Alabama in Huntsville,Huntsville,AL,0.7367,7358.0,Doctoral Universities: Very High Research Acti...,Public,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0127,0.0,0.0,0.0,0.0,0.0407,0.1341,0.1930,0.0073
Alabama State University,Montgomery,AL,0.9799,3495.0,Doctoral/Professional Universities,Public,0.0000,0.0000,0.0000,0.0000,...,0.0648,0.0196,0.0,0.0,0.0,0.0,0.0511,0.0904,0.1513,0.0059
The University of Alabama,Tuscaloosa,AL,0.7890,30725.0,Doctoral Universities: Very High Research Acti...,Public,0.0000,0.0061,0.0000,0.0019,...,0.0072,0.0661,0.0,0.0,0.0,0.0,0.0234,0.1077,0.2916,0.0096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Florida Academy of Nursing,Miramar,FL,0.3088,239.0,Not applicable,Private for-profit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,1.0000,0.0000,0.0000
Herzing University-Tampa,Tampa,FL,0.9630,68.0,Not applicable,Private nonprofit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000
Abilene Christian University-Undergraduate Online,Addison,TX,1.0000,415.0,Not applicable,Private nonprofit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000
Great Northern University,Spokane,WA,1.0000,25.0,Not applicable,Private nonprofit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.1250,0.0000
Arizona College of Nursing-Salt Lake City,Murray,UT,1.0000,186.0,Not applicable,Private for-profit,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0000,0.0000,0.0000,0.0000

We'll want to single out Cal Poly, which we can do like this.

In [12]:
school_name = "California Polytechnic State University-San Luis Obispo"

cp = df_college.loc[school_name]

cp

City                                                        San Luis Obispo
State                                                                    CA
AdmissionRate                                                          0.33
Undergraduates                                                      21090.0
CarnegieClassification    Master's Colleges & Universities: Larger Programs
Ownership                                                            Public
PCIP01                                                               0.1084
PCIP03                                                               0.0255
PCIP04                                                               0.0441
PCIP05                                                               0.0019
PCIP09                                                               0.0353
PCIP10                                                               0.0175
PCIP11                                                               0.0326
PCIP12                                                                  0.0
PCIP13                                                                0.013
PCIP14                                                               0.2314
PCIP15                                                                0.011
PCIP16                                                               0.0019
PCIP19                                                                  0.0
PCIP22                                                                  0.0
PCIP23                                                               0.0147
PCIP24                                                               0.0229
PCIP25                                                                  0.0
PCIP26                                                               0.0495
PCIP27                                                               0.0173
PCIP29                                                                  0.0
PCIP30                                                               0.0223
PCIP31                                                               0.0419
PCIP38                                                               0.0073
PCIP39                                                                  0.0
PCIP40                                                               0.0205
PCIP41                                                                  0.0
PCIP42                                                               0.0288
PCIP43                                                                  0.0
PCIP44                                                                  0.0
PCIP45                                                               0.0588
PCIP46                                                                  0.0
PCIP47                                                                  0.0
PCIP48                                                                  0.0
PCIP49                                                                  0.0
PCIP50                                                                0.013
PCIP51                                                                0.006
PCIP52                                                               0.1637
PCIP54                                                                0.011
Name: California Polytechnic State University-San Luis Obispo, dtype: object

1\. Based on only the admission rate and the number of undergraduates, what schools are most similar to Cal Poly? Specify how you're making this decision.

In [13]:
features_c1 = ["AdmissionRate", "Undergraduates"]
X_c = df_college[features_c1].dropna()
X_c_z = (X_c - X_c.mean()) / X_c.std()

diff_c = X_c_z - X_c_z.loc[school_name]
df_college["dist_c1"] = np.sqrt((diff_c**2).sum(axis=1))
df_college.sort_values("dist_c1")[features_c1 + ["dist_c1"]].head(10)

,AdmissionRate,Undergraduates,dist_c1
Institution,,,
California Polytechnic State University-San Luis Obispo,0.3300,21090.0,0.000000
University of California-Santa Barbara,0.2918,23081.0,0.309162
DeVry University-Illinois,0.4552,19729.0,0.593121
University of North Carolina at Chapel Hill,0.2040,19722.0,0.596846
Clemson University,0.4922,21577.0,0.736788
University of Virginia-Main Campus,0.2074,17041.0,0.761296
CUNY Hunter College,0.4590,17293.0,0.761441
Stony Brook University,0.4806,17900.0,0.795756
Boston University,0.1865,17501.0,0.797041
North Carolina State University at Raleigh,0.4748,24999.0,0.826264

**The University of California, Santa Barbara is the most similar to Cal Poly. I am deciding this based on the distance variable I calculated. UCSB has the smallest distance.**

2\. Now consider the admission rate, the number of undergraduates, and also the [Carnegie classification](https://en.wikipedia.org/wiki/Carnegie_Classification_of_Institutions_of_Higher_Education) of the type of school, and the ownership (public, private, etc.) Based on these variables, what schools are most similar to Cal Poly? Specify how you're making this decision.

In [14]:
features_c2 = [
    "AdmissionRate",
    "Undergraduates",
    "CarnegieClassification",
    "Ownership",
]
X_c2 = pd.get_dummies(
    df_college[features_c2].dropna(), drop_first=True
).astype(float)
X_c2_z = (X_c2 - X_c2.mean()) / X_c2.std()

diff_c2 = X_c2_z - X_c2_z.loc[school_name]
df_college["dist_c2"] = np.sqrt((diff_c2**2).sum(axis=1))
df_college.sort_values("dist_c2")[["dist_c2"]].head(10)

                                                     dist_c2
Institution
California Polytechnic State University-San Lui...  0.000000
CUNY Hunter College                                 0.761441
CUNY Bernard M Baruch College                       1.073601
CUNY John Jay College of Criminal Justice           1.184989
CUNY Brooklyn College                               1.376321
California State Polytechnic University-Pomona      1.450297
CUNY Queens College                                 1.491386
CUNY Lehman College                                 1.660905
The University of West Florida                      1.809410
State University of New York at New Paltz           2.014042

**CUNY Hunter College is the most similar to Cal Poly based on the euclidian distance I calculated. It has the smallest distance.**

3\. The columns whose names begin with "PCIP" contain the proportions of students at each school studying various fields (e.g., Engineering, Psychology). Each field is represented by a two-digit code called the [CIP code](https://nces.ed.gov/ipeds/cipcode/browse.aspx?y=55).

If we only consider the proportions of students studying various fields, what schools are most similar to Cal Poly? Specify how you're making this decision.

In [15]:
pcip_cols = [col for col in df_college.columns if col.startswith("PCIP")]
X_c3 = df_college[pcip_cols].fillna(0)
X_c3_z = (X_c3 - X_c3.mean()) / X_c3.std()

diff_c3 = X_c3_z - X_c3_z.loc[school_name]
df_college["dist_c3"] = np.sqrt((diff_c3**2).sum(axis=1))
df_college.sort_values("dist_c3")[["dist_c3"]].head(10)

                                                     dist_c3
Institution
California Polytechnic State University-San Lui...  0.000000
Iowa State University                               1.986207
California State Polytechnic University-Pomona      2.241726
Texas A & M University-College Station              2.258942
Mississippi State University                        2.335288
Clemson University                                  2.376870
North Carolina State University at Raleigh          2.508999
West Virginia University                            2.584194
Louisiana Tech University                           2.778706
Louisiana State University and Agricultural & M...  2.802481

**Iowa State University is the most similar to Cal Poly when we consider the proportions of students studying various fields. I am deciding this based on the euclidian distance I calculated, and determined that Iowa State University has the smallest distance.**